# Configure here which dependency updates should be merged automatically.
# The recommended configuration is the following:
- match:
    # Only merge patches for production dependencies
    dependency_type: all
    update_type: all
- match:
    # Except for security fixes, here we allow minor patches
    dependency_type: all
    update_type: all
- match:
    # and development dependencies can have a minor update, too
    dependency_type: all
    update_type: all

# The syntax is based on the legacy dependabot v1 automerged_updates syntax, see:
# https://dependabot.com/docs/config-file/#automerged_updates
